#!/usr/bin/env python3
# -*- coding: utf-8 -*-
##############################################################################
# Copyright (C) 2015-2020 EDF SA                                             #
#                                                                            #
# Author: Rémi Palancher <remi-externe.palancher@edf.fr>                     #
#                                                                            #
# This file is part of slurm-llnl-misc-plugins.                              #
#                                                                            #
# This software is governed by the CeCILL-C license under French law and     #
# abiding by the rules of distribution of free software. You can use,        #
# modify and/ or redistribute the software under the terms of the CeCILL-C   #
# license as circulated by CEA, CNRS and INRIA at the following URL          #
# "http://www.cecill.info".                                                  #
#                                                                            #
# As a counterpart to the access to the source code and rights to copy,      #
# modify and redistribute granted by the license, users are provided only    #
# with a limited warranty and the software's author, the holder of the       #
# economic rights, and the successive licensors have only limited            #
# liability.                                                                 #
#                                                                            #
# In this respect, the user's attention is drawn to the risks associated     #
# with loading, using, modifying and/or developing or reproducing the        #
# software by the user in light of its specific status of free software,     #
# that may mean that it is complicated to manipulate, and that also          #
# therefore means that it is reserved for developers and experienced         #
# professionals having in-depth computer knowledge. Users are therefore      #
# encouraged to load and test the software's suitability as regards their    #
# requirements in conditions enabling the security of their systems and/or   #
# data to be ensured and, more generally, to use and operate it in the       #
# same conditions as regards security.                                       #
#                                                                            #
# The fact that you are presently reading this means that you have had       #
# knowledge of the CeCILL-C license and that you accept its terms.           #
#                                                                            #
##############################################################################

import os
import sys
import configparser
import grp
import subprocess
import csv

import argparse

import logging
import logging.handlers

# conf global variable
conf = None
logger = None
args = None

DEFAULT_CONF_FILE = '/etc/slurm/sync-accounts.conf'

# This list specifies list of users that should normally be present in SlurmDBD
# but not necessarily in users groups, and therefore should not be removed from
# SlurmDBD.
IGNORED_SLURM_USERS = [ 'root' ]

class User(object):

    def __init__(self, name, group):

        self.name = name
        self.group = group

    def __eq__(self, other):

        return self.name == other.name

    def __hash__(self):

        return hash(self.name)

class Account(object):

    def __init__(self, name, desc, groups):

        self.name = name
        self.desc = desc
        self.groups = groups  # the posix groups associated to this account

class Conf(object):
    """Runtime configuration class"""

    def __init__(self, filename=DEFAULT_CONF_FILE):
        self.filename = filename
        self.org = None
        self.cluster = None
        self.groups = []
        self.policy = None

        # opts creation cmd params
        self.user_add_opts = None
        self.acct_add_opts = None

        # global_account/multiple_accounts policies specific params
        self.accounts = []

    def parse(self):
        """Parse the configuration file"""

        if not os.path.isfile(self.filename):
            die("failed to parse config file {filename}" \
                .format(filename=self.filename))

        parser = configparser.ConfigParser()
        parser.read(self.filename)

        self.cluster = parser.get('main', 'cluster')
        self.org = parser.get('main', 'org')

        self.policy = parser.get('main', 'policy')

        available_policies = [ 'global_account',
                               'multiple_accounts',
                               'user_account' ]

        if not self.policy in available_policies:
            die("invalid policy {policy}" \
                .format(policy=self.policy))

        if self.policy in [ 'global_account', 'user_account']:

            # check deprecated group parameter
            if not parser.has_option('main', 'groups') and \
               parser.has_option('main','group'):
                logger.error('main/group parameter is deprecated, '
                             'use main/groups instead')
                self.groups = [ parser.get('main', 'group') ]
            else:
                self.groups = parser.get('main', 'groups').split(',')

        if self.policy == 'global_account':
            acct_name = parser.get('global_account', 'name')
            acct_desc = parser.get('global_account', 'desc')
            logger.debug("global account %s for groups %s",
                         acct_name, str(self.groups))
            self.accounts.append(Account(acct_name, acct_desc, self.groups))

        if self.policy == 'multiple_accounts':
            # parse all account/* sections
            prefix = 'account/'
            all_sections = parser.sections()
            for section in parser.sections():
                if section.startswith(prefix):
                    acct_name = section[len(prefix):]
                    desc = parser.get(section, 'desc')
                    # check deprecated group parameter
                    if not parser.has_option(section, 'groups') and \
                       parser.has_option(section,'group'):
                        logger.error("%s/group parameter is deprecated, "
                                     "use %s/groups instead", section, section)
                        groups = [ parser.get(section, 'group') ]
                    else:
                        groups = parser.get(section, 'groups').split(',')

                    logger.debug("account %s for groups %s",
                                 acct_name, str(groups))
                    self.accounts.append(Account(acct_name, desc, groups))

        try:
            user_opts = parser.get('main', 'user_add_opts')
            if user_opts != '':
                self.user_add_opts = user_opts.split(' ')
            logger.debug("user_add_opts: %s", str(self.user_add_opts))
        except configparser.NoOptionError:
            # This option is not required in configuration file, then
            # self.user_add_opts stays None if not found.
            pass

        try:
            acct_opts = parser.get('main', 'acct_add_opts')
            if acct_opts != '':
                self.acct_add_opts = acct_opts.split(' ')
            logger.debug("acct_add_opts: %s", str(self.acct_add_opts))
        except configparser.NoOptionError:
            # This option is not required in configuration file, then
            # self.acct_add_opts stays None if not found.
            pass

def die(msg):

    logger.critical(msg)
    sys.exit(1)

def run_or_die(cmd):

    logger.debug("run: {cmd}".format(cmd=' '.join(cmd)))
    if args.dry_run is False:
        returncode = subprocess.call(cmd)
        if returncode:
            die("error while running command: {cmd}: {error}" \
                .format(cmd=' '.join(cmd), error=str(returncode)))

def get_posix_group_users(group):

    logger.debug("searching for users in group %s", group)
    entry = grp.getgrnam(group)
    return [ User(user.lower(), group) for user in entry[3] ]

def get_posix_groups_users(groups):

    users = []

    for group in groups:
        users.extend(get_posix_group_users(group))

    return list(set(users))  # remove duplicates

def get_posix_users():
    """Return a list of Users members of the posix groups set in
       configuration."""

    if len(conf.groups):
        return get_posix_groups_users(conf.groups)

    # merge users of all groups found in conf.accounts
    users = []
    for account in conf.accounts:
        xusers = get_posix_groups_users(account.groups)
        users.extend([ xuser for xuser in xusers if xuser not in users ])
    return users

def find_group_account(group):
    """Return the account name corresponding to the group in parameter."""
    for account in conf.accounts:
        if group in account.groups:
            return account.name
    raise IndexError("no account found for group %s" % (group))

def check_acct(name):

    cmd = [ 'sacctmgr', '-n', 'show', 'Account', name ]
    logger.debug("run: {cmd}".format(cmd=' '.join(cmd)))
    output = subprocess.Popen(cmd, stdout=subprocess.PIPE).communicate()[0]
    return len(output) > 0

def create_acct(name, desc):

    logger.info("creating account {acct}".format(acct=name))
    cmd = ['sacctmgr', '-i', 'add', 'account', name,
           "Cluster='{cluster}'".format(cluster=conf.cluster),
           "Description='{desc}'".format(desc=desc),
           "Organization='{org}'".format(org=conf.org) ]
    if conf.acct_add_opts is not None:
        cmd.extend(conf.acct_add_opts)
    run_or_die(cmd)

def ensure_acct(name, desc):

    if check_acct(name) is False:
        create_acct(name, desc)

def remove_acct(name):

    logger.info("deleting account {acct}".format(acct=name))
    cmd = [ 'sacctmgr', '-i', 'delete', 'account', name ]
    run_or_die(cmd)

def create_user(name, account):

    logger.info("creating user {user}".format(user=name))
    cmd = [ 'sacctmgr', '-i', 'add', 'user', name,
            "DefaultAccount={acct}".format(acct=account) ]
    if conf.user_add_opts is not None:
        cmd.extend(conf.user_add_opts)
    run_or_die(cmd)

def remove_user(name):

    logger.info("deleting user {user}".format(user=name))
    cmd = [ 'sacctmgr', '-i', 'delete', 'user', name ]
    run_or_die(cmd)

def get_slurm_users():

    users = []
    cmd = [ 'sacctmgr', 'show', 'user', '--parsable', '--noheader' ]
    logger.debug("run: {cmd}".format(cmd=' '.join(cmd)))
    output = subprocess.Popen(cmd, stdout=subprocess.PIPE).communicate()[0].decode('utf-8')
    reader = csv.reader(output.strip().split('\n'), delimiter='|')
    for row in reader:
        user = row[0]
        if user not in IGNORED_SLURM_USERS:
            users.append(user)

    return users

def parse_args():

    global args
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", help="Do nothing, just print what it would do.", action="store_true")
    parser.add_argument("--debug", help="Debug mode.", action="store_true")
    args = parser.parse_args()

def init_logger():

    global logger
    logger = logging.getLogger(__file__)
    if args.debug is True:
        logger.setLevel(logging.DEBUG)
    else:
        logger.setLevel(logging.INFO)

    if args.debug is True or args.dry_run is True:
        handler = logging.StreamHandler()
        formatter = logging.Formatter('%(levelname)s: %(message)s')
    else:
        handler = logging.handlers.SysLogHandler(address='/dev/log')
        formatter = logging.Formatter('%(name)s - %(levelname)s - %(message)s')

    handler.setFormatter(formatter)
    logger.addHandler(handler)

def main():

    global conf

    parse_args()
    init_logger()

    conf = Conf()
    conf.parse()

    if conf.policy != 'user_account':
        for account in conf.accounts:
            ensure_acct(account.name, account.desc)

    users_posix = get_posix_users()
    users_slurm = get_slurm_users()

    for user in users_posix:
        if user.name not in users_slurm:
            # create user and eventually account
            if conf.policy == 'user_account':
                acct_desc = "user {user} default account".format(user=user.name)
                create_acct(user.name, acct_desc)
                create_user(user.name, user.name)
            elif conf.policy in ['global_account', 'multiple_accounts']:
                acct = find_group_account(user.group)
                create_user(user.name, acct)

    for user in users_slurm:
        posix_user_names = [ xuser.name for xuser in users_posix ]
        if user not in posix_user_names:
            # delete user and eventually account
            remove_user(user)
            if conf.policy == 'user_account':
                remove_acct(user)

if __name__ == '__main__':

    main()
